### ISSUE TITLE
bid_acq segfaults

### ISSUE THREAD

**Issue by drzraf** [PADL/libbrowserid#4]
```
sed -i 's/clang/gcc -O0 -ggdb/ libbrowserid/tests/Makefile
```

```
$ cd tests; LD_LIBRARY_PATH=../.libs:~/src/jansson/src/.libs gdb ./bid_acq
```

```
Using host libthread_db library "/lib64/libthread_db.so.1".
*** Error in ~/src/gss_browserid/libbrowserid/tests/bid_acq': free(): invalid pointer: 0x0000000000619940 ***
[...]
#3  0x00007ffff701a1d6 in _int_free () from /lib64/libc.so.6
#4  0x00007ffff77cb4e1 in BIDReleaseContext (context=0x6197b0) at bid_context.c:297
#5  0x0000000000400fa3 in main (argc=1, argv=0x7fffffffd778) at bid_acq.c:139
```

**Comment by lhoward** [comment]
please try with 9bf92de5c8be1c387762cbbd3c933e9d732196f7
